# Generated by Django 5.1.3 on 2024-11-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_guest',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
