# Generated by Django 5.1 on 2024-11-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocuments',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
