# Generated by Django 5.1 on 2024-11-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futsal',
            name='district',
        ),
        migrations.RemoveField(
            model_name='futsal',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='futsal',
            name='province',
        ),
        migrations.RemoveField(
            model_name='futsal',
            name='tole',
        ),
        migrations.RemoveField(
            model_name='futsal',
            name='ward',
        ),
    ]
