# Generated by Django 5.1 on 2024-11-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0002_remove_futsal_district_remove_futsal_municipality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futsal',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='futsal',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
    ]
