# Generated by Django 5.1 on 2024-11-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0003_alter_futsal_latitude_alter_futsal_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futsal',
            name='latitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='futsal',
            name='longitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=20, max_digits=30, null=True),
        ),
    ]
